<a href="https://colab.research.google.com/github/shekhs/100-days-of-machine-learning/blob/main/tf_try.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf

In [4]:
X = tf.Variable([[-3,2,4],[2,0,-2],[5,2,3]])

In [5]:
X

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[-3,  2,  4],
       [ 2,  0, -2],
       [ 5,  2,  3]], dtype=int32)>

In [6]:
tf.reshape(X,shape=(9,1))

<tf.Tensor: shape=(9, 1), dtype=int32, numpy=
array([[-3],
       [ 2],
       [ 4],
       [ 2],
       [ 0],
       [-2],
       [ 5],
       [ 2],
       [ 3]], dtype=int32)>

In [7]:
X

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[-3,  2,  4],
       [ 2,  0, -2],
       [ 5,  2,  3]], dtype=int32)>

In [9]:
tf.reshape(X,shape=(1,9))

<tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[-3,  2,  4,  2,  0, -2,  5,  2,  3]], dtype=int32)>

In [15]:
y = tf.Variable([[2,1,2],[1,7,3],[1,1,1]]
                ,[[2,1,2],[1,7,3],[2,1,2]])

In [16]:
a = X*y

In [17]:
a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[-6,  2,  8],
       [ 2,  0, -6],
       [ 5,  2,  3]], dtype=int32)>

In [23]:
x = tf.Variable(3.0)
with tf.GradientTape() as tape:
  y = 3.0*tf.math.log(x)


In [24]:
y

<tf.Tensor: shape=(), dtype=float32, numpy=3.295837>

In [25]:
dy_dx = tape.gradient(y,x)


In [26]:
dy_dx

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [27]:
x

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>

In [29]:
x = tf.Variable([10], dtype=float)

with tf.GradientTape() as tape:
 y = tf.pow(3,x*0.2) + 5*tf.pow(x,2) - tf.math.log(x) + tf.math.tanh(x)

dy_dx = tape.gradient(y,x)
dy_dx

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([101.8775], dtype=float32)>

In [30]:
x = tf.Variable((10), dtype=tf.float32)
with tf.GradientTape() as tape:
  y = tf.pow(3, 0.2 * x) + 5* tf.pow(x,2) - tf.math.log(x) + tf.math.tanh (x)
dy_dx = tape.gradient(y,x)
print("The slope of the function at x = 10 is ", dy_dx.numpy())

The slope of the function at x = 10 is  101.8775


In [48]:
x = tf.Variable((10), dtype=tf.float32)
xx = tf.Variable((4), dtype=tf.float32)
with tf.GradientTape() as tape:
  y = tf.pow(3, 0.2 * x) + 5* tf.pow(x,2) - tf.math.log(x) + tf.math.tanh (x)
dy_dx = tape.gradient(y,x)
print("The slope of the function at x = 10 is ", dy_dx.numpy())
#print("The slope of the function at x = 4 is ", kk.numpy())

The slope of the function at x = 10 is  101.8775


In [44]:
X = tf.Variable(tf.random.normal((1,)))

In [45]:
X

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.33023047], dtype=float32)>